In [ ]:
#data types 
# i - integer
# b - boolean
# u - unsigned integer 
# f - float
# c - complex float
# s - string

In [1]:
import numpy as np
a = np.array([2,4,6,8])
print(type(a))

<class 'numpy.ndarray'>


In [2]:
print(a.dtype)

int32


In [4]:
b = np.array(["raj","kumar","santhosh"])
print(b.dtype)
#U : Represents a unicode string data type in numpy
#3 : indicates the maximum length of each string in the array, interms of unicode characters.

<U8


In [5]:
c = np.array([3.2,4.7])
print(c.dtype)

float64


In [6]:
e = np.array([1+2j])
print(e.dtype)

complex128


In [7]:
f = np.array([1,2,3,4])
print(f.dtype)

int32


In [10]:
g = np.array([1,2,3,4],dtype = 'S')
print(g.dtype) # byte string

|S1


In [15]:
# i8 mention size
h = np.array([1, 2, 3, 4], dtype='i8')

print(h)
print(h.dtype)


[1 2 3 4]
int64


In [16]:
# can't change integer 
i = np.array(['a', '2', '3'], dtype='i2')
i

ValueError: invalid literal for int() with base 10: 'a'

In [21]:
a1 = np.array(['a', 'jdk', '33'], dtype='S')
print(a1)
print(a1.dtype)

[b'a' b'jdk' b'33']
|S3


In [22]:
a2 = np.array(['1', '2', '3'], dtype='i8')
print(a2)
print(a2.dtype)

[1 2 3]
int64


In [23]:
b1=a2.astype("S")
b1

array([b'1', b'2', b'3'], dtype='|S21')

In [25]:
new = np.array([1.1, 2.1, 3.1])
newarr = new.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [26]:
val1 = np.array(["1", "2", "3"])
values = val1.astype("i8")
print(values)
print(values.dtype)

[1 2 3]
int64


In [28]:
val2 = np.array([1, 2, 3])
values = val2.astype(bool)
print(values)
print(values.dtype)

[ True  True  True]
bool


In [30]:
#copy and view 
import numpy as np
a = np.array([1,2,3,4])
x = a.copy()
x[0] = 23
print(a)
print(x)

[1 2 3 4]
[23  2  3  4]


In [31]:
a = np.array([1,2,3,4])
x = a.view()
x[0] = 23
print(a)
print(x)

[23  2  3  4]
[23  2  3  4]


In [32]:
#numpy arthematic operations 
# Arrays
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([[4, 5, 6],[1, 2, 3]])

# Operations
addition = a + b         # [5, 7, 9]
subtraction = a - b      # [-3, -3, -3]
multiplication = a * b   # [4, 10, 18]
division = a / b         # [0.25, 0.4, 0.5]

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [[5 7 9]
 [2 4 6]]
Subtraction: [[-3 -3 -3]
 [ 0  0  0]]
Multiplication: [[ 4 10 18]
 [ 1  4  9]]
Division: [[0.25 0.4  0.5 ]
 [1.   1.   1.  ]]


In [5]:
val1 = [1,2,3]
print(val1)
val2 = [4,5,6]
print(val2)
val3 = list(zip(val1,val2))
print(val3

[1, 2, 3]
[4, 5, 6]
