In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
np.__version__

'1.26.4'

In [2]:
import numpy as np

In [5]:
value = np.array([1,2,3,4,5])
print(value)

[1 2 3 4 5]


In [6]:
print(type(value))

<class 'numpy.ndarray'>


In [ ]:
# Dimensions in array 
#types of arrays 
'''  0 dimensional array
     1 dimensional array
     2 dimensional array
     3 dimensional array '''

In [9]:
# 0 dimensional array 
import numpy as np 
a = np.array(40)
print(a)
print(a.ndim, "dimensional")

40
0 dimensional


In [10]:
# 1 dimensional array 
import numpy as np 
a = np.array([40,23,43,76,34])
print(a)
print(a.ndim, "dimensional")

[40 23 43 76 34]
1 dimensional


In [11]:
# 2 dimensional array 
import numpy as np 
a = np.array([[40,23,43,76,34],[43,87,12,21,11]])
print(a)
print(a.ndim, "dimensional")

[[40 23 43 76 34]
 [43 87 12 21 11]]
2 dimensional


In [12]:
# 3 dimensional array 
import numpy as np 
a = np.array([[[40,23,43,76,34],[43,23,67,98,12]],[[21,23,45,66,87],[12,65,13,87,56]]])
print(a)
print(a.ndim, "dimensional")

[[[40 23 43 76 34]
  [43 23 67 98 12]]

 [[21 23 45 66 87]
  [12 65 13 87 56]]]
3 dimensional


In [14]:
#array indexing 
a = np.array([2,4,6,8,10])
print(a[1])

4


In [16]:
a = np.array([[2,4,6],[8,10,12]])
print(a[1][1])

10


In [18]:
a = np.array([[2,4,6],[8,10,12]])
print(a[0,1])

4


In [21]:
d = np.array([[[4, 5],[19,22]],[[4, 5],[9,10]]])
d[1,1,1]

10

In [22]:
d[0,1,1]

22

In [23]:
d[1]

array([[ 4,  5],
       [ 9, 10]])

In [24]:
d[0,1]

array([19, 22])

In [25]:
#array slicing
val = np.array([2,4,56,7,7,65,32])
print(val[0:4])

[ 2  4 56  7]


In [28]:
val = np.array([2,4,56,7,7,65,32])
print(val[1:7])
print(val[1:])

[ 4 56  7  7 65 32]
[ 4 56  7  7 65 32]


In [29]:
val = np.array([2,4,56,7,7,65,32])
print(val[-5:-1])

[56  7  7 65]


In [30]:
val = np.array([[2,4,56],[7,65,32]])
print(val[0,1:])

[ 4 56]
